spring:
  application:
    name: trends-service
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        default-requeue-rejected: false
server:
  port: 8083

smartlife:
  events:
    exchange: eventos
    routing-keys:
      venta-registrada: venta.registrada
    queues:
      venta-registrada: trends.venta-registrada.queue
